### ISSUE TITLE
в целях сеошности сделать на страницах без текста какой-нибудь текст

### ISSUE THREAD

**Issue by LookNya** [genshin-base/main-site#15]
а то везде выводится текст из футера
![image](https://user-images.githubusercontent.com/7099453/163691529-c689caa8-8646-436d-98ea-a07257d74cd0.png)

**Comment by 3bl3gamer** [comment]
`<meta name="description" content="..."/>`

https://developers.google.com/search/docs/advanced/appearance/snippet
